In [1]:
import wave
import numpy as np
import matplotlib.pyplot as plt


#loading the audio file as wave object
hello_world = wave.open("Hello-World.wav", "r")

In [2]:
#convert wave object to byte 
hello_world_soundwave =  hello_world.readframes(-1)

In [3]:
#View the files in byte form
hello_world_soundwave[:10]

b'\xed\xff\xde\xff\xe4\xff\xf2\xff\xf1\xff'

<b>Converting soundwave byte to interger</b>

In [4]:
#convert from byte to interger
singnal_hw = np.frombuffer(hello_world_soundwave, dtype='int16')

In [5]:
#show the first 10 items
singnal_hw[:10]

array([-19, -34, -28, -14, -15,   1, -22, -20,  -3, -22], dtype=int16)

<b>Finding the frame rate</b>

In [6]:
#get the frame rate
framerate_hw = hello_world.getframerate()

#Show the frame rate
framerate_hw

22050

<b>Finding Soundwave timestamp</b>

In [7]:
#Return evenly spaced values between start and stop
np.linspace(start=1, stop=10, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
#Get the timestamp of the good morning soundwave
time_hw = np.linspace(start=0, 
                     stop=len(hello_world_soundwave)/framerate_hw,
                     num=len(hello_world_soundwave))

In [9]:
#View first 10 timestamp of good morning soundwave
time_hw[:10]

array([0.00000000e+00, 4.53519881e-05, 9.07039762e-05, 1.36055964e-04,
       1.81407952e-04, 2.26759941e-04, 2.72111929e-04, 3.17463917e-04,
       3.62815905e-04, 4.08167893e-04])

<b>Visualizing sound waves</b>

In [10]:
#add another sound wave
hello_erick = wave.open("Hello-Erick.wav", "r")

#convert wave object to byte 
hello_erick_soundwave =  hello_erick.readframes(-1)

#convert from byte to interger
singnal_he = np.frombuffer(hello_erick_soundwave, dtype='int16')

#get the frame rate
framerate_he = hello_erick.getframerate()


#Get the timestamp of the good morning soundwave
time_he = np.linspace(start=0, 
                     stop=len(hello_erick_soundwave)/framerate_he,
                     num=len(hello_erick_soundwave))


In [11]:
#lets get the frame rate of the new hello Erick
framerate_he

22050

In [ ]:
#Initalize figures and seting up titles
plt.title("Hello Erick  vs Hello World")
plt.xlabel("Time (seconds)")
plt.ylabel("Amplitude")

#adding good morining and good afternoon values
plt.plot(time_he, hello_erick_soundwave, lebel="Hello Erick")
plt.plot(time_hw, hello_world_soundwave, lebel="Hello World", alpha=0.5)

#Create legend and show our plot
plt.legend()
plt.show()

In [12]:
import speech_recognition as sr

In [13]:
recognizer =  sr.Recognizer()

#setting the energy threashold
recognizer.energy_treshold = 300

In [14]:
#Read in audio files
clean_hello_world = sr.AudioFile("Hello-World.wav")

#Type of our audio file
type(clean_hello_world)

speech_recognition.AudioFile

In [16]:
#Convert From AudioFile to AudioData 
with clean_hello_world as source:
    
    #Record the audio 
    clean_audio_hello_world = recognizer.record(source)
    

#Check the type 
type(clean_audio_hello_world)


speech_recognition.AudioData

In [18]:
#Transcribe clean_support_call

recognizer.recognize_google(audio_data= clean_audio_hello_world)

'hello world'